/**
 * Mock Data for Development
 */

import type { 
  IUser, 
  IWorkshop, 
  ICertificate, 
  ITestimonial, 
  IFeedback, 
  IAnalytics,
  IWorkshopParticipant,
  IRawZoomLog,
  IJoyCoinTransaction
} from './schemas';

export const mockUsers: IUser[] = [
  {
    _id: '1',
    email: 'admin@happiness.com',
    name: 'Admin User',
    password: 'hashed_password_123',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    bio: 'Platform administrator',
    happinessScore: 8.5,
    certificatesCount: 5,
    workshopsAttended: 12,
    workshopsBooked: 15,
    joyCoins: 250, // 💰 Initial balance
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '2',
    email: 'trainer@happiness.com',
    name: 'Dr. Sarah Johnson',
    password: 'hashed_password_456',
    role: 'trainer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer',
    bio: 'Certified Happiness & Well-being Coach',
    company: 'Wellness Institute',
    happinessScore: 9.2,
    certificatesCount: 8,
    workshopsAttended: 20,
    workshopsBooked: 18,
    joyCoins: 420, // 💰 Initial balance
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '3',
    email: 'volunteer@happiness.com',
    name: 'John Smith',
    password: 'hashed_password_789',
    role: 'volunteer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=volunteer',
    bio: 'Passionate wellness volunteer',
    happinessScore: 8.1,
    certificatesCount: 3,
    workshopsAttended: 8,
    workshopsBooked: 10,
    joyCoins: 160, // 💰 Initial balance
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '4',
    email: 'participant@happiness.com',
    name: 'Emma Wilson',
    password: 'hashed_password_101',
    role: 'participant',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    bio: 'Wellness enthusiast',
    location: 'New York, NY',
    happinessScore: 7.8,
    certificatesCount: 2,
    workshopsAttended: 5,
    workshopsBooked: 8,
    joyCoins: 180, // 💰 Initial balance
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '5',
    email: 'basiak@happiness.com',
    name: 'Basiak',
    password: 'hashed_password_102',
    role: 'participant',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=basiak',
    bio: 'Recently attended our workshops',
    happinessScore: 8.3,
    certificatesCount: 1,
    workshopsAttended: 2,
    workshopsBooked: 3,
    joyCoins: 160, // 💰 Initial balance
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '6',
    email: 'partner@happiness.com',
    name: 'Partnership Manager',
    password: 'hashed_password_103',
    role: 'partner',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=partner',
    bio: 'Partner organization manager',
    happinessScore: 8.0,
    certificatesCount: 0,
    workshopsAttended: 0,
    workshopsBooked: 5,
    joyCoins: 280, // 💰 Initial balance
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '7',
    email: 'donor@happiness.com',
    name: 'Generous Donor',
    password: 'hashed_password_104',
    role: 'donor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=donor',
    bio: 'Supporting the mission',
    happinessScore: 8.2,
    certificatesCount: 0,
    workshopsAttended: 1,
    workshopsBooked: 0,
    joyCoins: 600, // 💰 Initial balance
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '8',
    email: 'rwa@happiness.com',
    name: 'RWA Community Lead',
    password: 'hashed_password_105',
    role: 'rwa',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rwa',
    bio: 'Residential welfare association',
    happinessScore: 8.1,
    certificatesCount: 0,
    workshopsAttended: 3,
    workshopsBooked: 8,
    joyCoins: 240, // 💰 Initial balance
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '9',
    email: 'phd@happiness.com',
    name: 'Dr. Research Scholar',
    password: 'hashed_password_106',
    role: 'phd-scholar',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=phd',
    bio: 'Research and academic studies',
    happinessScore: 8.7,
    certificatesCount: 10,
    workshopsAttended: 25,
    workshopsBooked: 20,
    joyCoins: 550, // 💰 Initial balance
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '10',
    email: 'director@happiness.com',
    name: 'Executive Director',
    password: 'hashed_password_107',
    role: 'director',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=director',
    bio: 'Organization leadership',
    happinessScore: 8.8,
    certificatesCount: 12,
    workshopsAttended: 30,
    workshopsBooked: 35,
    joyCoins: 500, // 💰 Initial balance
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '11',
    email: 'coadmin@happiness.com',
    name: 'Co-Administrator',
    password: 'hashed_password_108',
    role: 'co-admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coadmin',
    bio: 'Administrative support',
    happinessScore: 8.4,
    certificatesCount: 6,
    workshopsAttended: 15,
    workshopsBooked: 12,
    joyCoins: 380, // 💰 Initial balance
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-02'),
  },
];

export const mockWorkshops: IWorkshop[] = [
  {
    _id: '1',
    title: 'Mindfulness & Meditation Basics',
    description:
      'Learn fundamental mindfulness techniques and meditation practices to reduce stress and increase well-being.',
    category: 'Mental Health',
    date: new Date('2024-02-15'),
    time: '19:00',
    duration: 60,
    location: 'New York, NY',
    mode: 'hybrid',
    maxCapacity: 30,
    currentEnrollment: 3,
    trainer: '2', // Dr. Sarah Johnson
    trainerName: 'Dr. Sarah Johnson',
    trainerBio: 'Certified Happiness & Well-being Coach with 10+ years of experience',
    trainerContact: {
      email: 'trainer@happiness.com',
      phone: '+1 (555) 123-4567',
    },
    status: 'published',
    locationDetails: {
      address: '123 Wellness Street',
      city: 'New York',
      state: 'NY',
      mapUrl: 'https://maps.google.com/?q=New+York+NY',
    },
    averageRating: 4.8,
    totalRatings: 15,
    feedbackComments: [
      {
        userId: '4',
        userName: 'Emma Wilson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
        comment: 'Life-changing workshop! The mindfulness techniques are so practical.',
        rating: 5,
        createdAt: new Date('2024-02-16'),
      },
      {
        userId: '5',
        userName: 'Basiak',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=basiak',
        comment: 'Dr. Sarah is an excellent instructor. Highly recommend!',
        rating: 5,
        createdAt: new Date('2024-02-16'),
      },
    ],
    likes: ['4', '5', '3'],
    shares: 8,
    joyCoinsReward: 20, // 💰 Reward for completing
    isProcessed: false,
    registrations: [
      { userId: '4', status: 'attended', registeredAt: new Date('2024-02-10') },
      { userId: '5', status: 'attended', registeredAt: new Date('2024-02-10') },
      { userId: '1', status: 'booked', registeredAt: new Date('2024-02-11') },
    ],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '2',
    title: 'Yoga for Happiness',
    description:
      'Explore yoga practices designed to enhance physical and emotional well-being through movement and breathwork.',
    category: 'Physical Health',
    date: new Date('2024-02-20'),
    time: '18:00',
    duration: 90,
    location: 'Los Angeles, CA',
    mode: 'offline',
    maxCapacity: 25,
    currentEnrollment: 2,
    trainer: '2',
    trainerName: 'Dr. Sarah Johnson',
    trainerBio: 'Certified Happiness & Well-being Coach with 10+ years of experience',
    trainerContact: {
      email: 'trainer@happiness.com',
      phone: '+1 (555) 123-4567',
    },
    status: 'published',
    locationDetails: {
      address: '456 Wellness Avenue',
      city: 'Los Angeles',
      state: 'CA',
      mapUrl: 'https://maps.google.com/?q=Los+Angeles+CA',
    },
    averageRating: 4.5,
    totalRatings: 8,
    feedbackComments: [],
    likes: ['4'],
    shares: 3,
    joyCoinsReward: 20,
    isProcessed: false,
    registrations: [
      { userId: '4', status: 'booked', registeredAt: new Date('2024-02-05') },
      { userId: '5', status: 'interested', registeredAt: new Date('2024-02-08') },
    ],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '3',
    title: 'Nutrition & Wellness',
    description: 'Discover how proper nutrition impacts your happiness and overall well-being.',
    category: 'Health',
    date: new Date('2024-02-25'),
    time: '14:00',
    duration: 120,
    location: 'Chicago, IL',
    mode: 'online',
    maxCapacity: 40,
    currentEnrollment: 1,
    trainer: '2',
    trainerName: 'Dr. Sarah Johnson',
    trainerBio: 'Certified Happiness & Well-being Coach with 10+ years of experience',
    trainerContact: {
      email: 'trainer@happiness.com',
      phone: '+1 (555) 123-4567',
    },
    status: 'published',
    locationDetails: {
      address: 'Virtual - Zoom Link Provided',
      city: 'Chicago',
      state: 'IL',
      mapUrl: '',
    },
    averageRating: 4.2,
    totalRatings: 5,
    feedbackComments: [],
    likes: [],
    shares: 2,
    zoomJoinUrl: 'https://zoom.us/j/1234567890',
    zoomMeetingId: '123 456 7890',
    zoomPassword: 'wellness123',
    joyCoinsReward: 20,
    isProcessed: false,
    registrations: [
      { userId: '4', status: 'booked', registeredAt: new Date('2024-02-02') },
    ],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '4',
    title: 'Positive Psychology in Practice',
    description: 'Dive deep into the science of happiness and learn evidence-based techniques to cultivate lasting well-being, gratitude, and resilience in your daily life.',
    category: 'Mental Health',
    date: new Date('2026-03-10'),
    time: '16:00',
    duration: 120,
    location: 'San Francisco, CA',
    mode: 'hybrid',
    maxCapacity: 35,
    currentEnrollment: 8,
    trainer: '2',
    trainerName: 'Dr. Sarah Johnson',
    trainerBio: 'Certified Happiness & Well-being Coach with 10+ years of experience in positive psychology',
    trainerContact: {
      email: 'trainer@happiness.com',
      phone: '+1 (555) 123-4567',
    },
    poster: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    status: 'published',
    locationDetails: {
      address: '789 Mindful Lane, Suite 200',
      city: 'San Francisco',
      state: 'CA',
      coordinates: {
        lat: 37.7749,
        lng: -122.4194,
      },
      mapUrl: 'https://maps.google.com/?q=San+Francisco+CA+789+Mindful+Lane',
    },
    averageRating: 4.9,
    totalRatings: 22,
    feedbackComments: [
      {
        userId: '3',
        userName: 'John Smith',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=volunteer',
        comment: 'The best workshop I have ever attended! Dr. Sarah brings such depth and warmth to positive psychology. The practical exercises changed how I approach each day.',
        rating: 5,
        createdAt: new Date('2026-02-05'),
      },
      {
        userId: '6',
        userName: 'Partnership Manager',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=partner',
        comment: 'Outstanding content and delivery. The gratitude practices have been transformative for our entire team.',
        rating: 5,
        createdAt: new Date('2026-02-04'),
      },
    ],
    likes: ['3', '6', '8', '9'],
    shares: 12,
    zoomJoinUrl: 'https://zoom.us/j/9876543210',
    zoomMeetingId: '987 654 3210',
    zoomPassword: 'positive2026',
    joyCoinsReward: 30,
    isProcessed: false,
    registrations: [
      { userId: '3', status: 'booked', registeredAt: new Date('2026-02-01') },
      { userId: '6', status: 'booked', registeredAt: new Date('2026-02-02') },
      { userId: '8', status: 'interested', registeredAt: new Date('2026-02-03') },
      { userId: '9', status: 'booked', registeredAt: new Date('2026-02-04') },
    ],
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-02-07'),
  },
];

export const mockCertificates: ICertificate[] = [
  {
    _id: '1',
    userId: '4',
    workshopId: '1',
    workshopTitle: 'Mindfulness & Meditation Basics',
    trainerName: 'Dr. Sarah Johnson',
    issuedDate: new Date('2024-02-15'),
    certificateNumber: 'HWBD-2024-001-EMMA',
    status: 'issued',
    sharedOn: ['twitter', 'linkedin'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-16'),
  },
  {
    _id: '2',
    userId: '5',
    workshopId: '1',
    workshopTitle: 'Mindfulness & Meditation Basics',
    trainerName: 'Dr. Sarah Johnson',
    issuedDate: new Date('2024-02-15'),
    certificateNumber: 'HWBD-2024-001-BASIAK',
    status: 'issued',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockTestimonials: ITestimonial[] = [
  {
    _id: '1',
    userId: '4',
    userName: 'Emma Wilson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    workshopId: '1',
    rating: 5,
    text: 'This workshop completely changed my perspective on happiness. Dr. Sarah is an amazing instructor!',
    isPublished: true,
    createdAt: new Date('2024-02-16'),
    updatedAt: new Date('2024-02-16'),
  },
  {
    _id: '2',
    userId: '5',
    userName: 'Basiak',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=basiak',
    workshopId: '1',
    rating: 5,
    text: 'The ny oath entertainment! The ny oath entertainist!',
    isPublished: true,
    createdAt: new Date('2024-02-16'),
    updatedAt: new Date('2024-02-16'),
  },
];

export const mockFeedback: IFeedback[] = [
  {
    _id: '1',
    userId: '4',
    workshopId: '1',
    rating: 5,
    comments: 'Excellent workshop with practical techniques',
    improvements: ['More interactive exercises', 'Longer sessions'],
    likelihood: 9,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockAnalytics: IAnalytics = {
  date: new Date('2024-02-02'),
  totalUsers: 5,
  totalWorkshops: 3,
  totalAttendances: 6,
  averageHappiness: 8.38,
  happinessTrend: [
    { date: new Date('2024-01-01'), score: 7.2 },
    { date: new Date('2024-01-08'), score: 7.5 },
    { date: new Date('2024-01-15'), score: 7.8 },
    { date: new Date('2024-01-22'), score: 8.0 },
    { date: new Date('2024-01-29'), score: 8.2 },
    { date: new Date('2024-02-02'), score: 8.38 },
  ],
  emotionBreakdown: [
    { emoji: '😊', count: 65, percentage: 45 },
    { emoji: '😍', count: 55, percentage: 38 },
    { emoji: '😎', count: 25, percentage: 17 },
  ],
  createdAt: new Date('2024-02-02'),
  updatedAt: new Date('2024-02-02'),
};

// 📊 ZOOM TRACKING DATA
export const workshopParticipants: IWorkshopParticipant[] = [];
export const rawZoomLogs: IRawZoomLog[] = [];
export const joyCoins: IJoyCoinTransaction[] = [];

// Member Applications - initially empty, filled when users submit
export const memberApplications: any[] = [];

export const mockDatabase = {
  users: mockUsers,
  workshops: mockWorkshops,
  certificates: mockCertificates,
  testimonials: mockTestimonials,
  feedback: mockFeedback,
  analytics: mockAnalytics,
  workshopParticipants,
  rawZoomLogs,
  joyCoins,
  memberApplications,
};

// 🌐 Export mutable references for API routes
export const users = mockUsers;
export const workshops = mockWorkshops;
export const certificates = mockCertificates;
export const testimonials = mockTestimonials;
export const feedback = mockFeedback;
export const analytics = mockAnalytics;

// 🌐 Mutable in-memory database for development
export const memoryDb = {
  users: mockUsers,
  workshops: mockWorkshops,
  certificates: mockCertificates,
  testimonials: mockTestimonials,
  feedback: mockFeedback,
  analytics: mockAnalytics,
  memberApplications,
};
