/**
 * Mock Data for Development
 */

import type { IUser, IWorkshop, ICertificate, ITestimonial, IFeedback, IAnalytics } from './schemas';

export const mockUsers: IUser[] = [
  {
    _id: '1',
    email: 'admin@happiness.com',
    name: 'Admin User',
    password: 'hashed_password_123',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    bio: 'Platform administrator',
    happinessScore: 8.5,
    certificatesCount: 5,
    workshopsAttended: 12,
    workshopsBooked: 15,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '2',
    email: 'trainer@happiness.com',
    name: 'Dr. Sarah Johnson',
    password: 'hashed_password_456',
    role: 'trainer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer',
    bio: 'Certified Happiness & Well-being Coach',
    company: 'Wellness Institute',
    happinessScore: 9.2,
    certificatesCount: 8,
    workshopsAttended: 20,
    workshopsBooked: 18,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '3',
    email: 'volunteer@happiness.com',
    name: 'John Smith',
    password: 'hashed_password_789',
    role: 'volunteer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=volunteer',
    bio: 'Passionate wellness volunteer',
    happinessScore: 8.1,
    certificatesCount: 3,
    workshopsAttended: 8,
    workshopsBooked: 10,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '4',
    email: 'participant@happiness.com',
    name: 'Emma Wilson',
    password: 'hashed_password_101',
    role: 'participant',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    bio: 'Wellness enthusiast',
    location: 'New York, NY',
    happinessScore: 7.8,
    certificatesCount: 2,
    workshopsAttended: 5,
    workshopsBooked: 8,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '5',
    email: 'basiak@happiness.com',
    name: 'Basiak',
    password: 'hashed_password_102',
    role: 'participant',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=basiak',
    bio: 'Recently attended our workshops',
    happinessScore: 8.3,
    certificatesCount: 1,
    workshopsAttended: 2,
    workshopsBooked: 3,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
];

export const mockWorkshops: IWorkshop[] = [
  {
    _id: '1',
    title: 'Mindfulness & Meditation Basics',
    description:
      'Learn fundamental mindfulness techniques and meditation practices to reduce stress and increase well-being.',
    category: 'Mental Health',
    date: new Date('2024-02-15'),
    time: '19:00',
    duration: 60,
    location: 'New York, NY',
    maxCapacity: 30,
    trainer: '2', // Dr. Sarah Johnson
    status: 'published',
    registrations: [
      { userId: '4', status: 'attended', registeredAt: new Date('2024-02-10') },
      { userId: '5', status: 'attended', registeredAt: new Date('2024-02-10') },
      { userId: '1', status: 'booked', registeredAt: new Date('2024-02-11') },
    ],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '2',
    title: 'Yoga for Happiness',
    description:
      'Explore yoga practices designed to enhance physical and emotional well-being through movement and breathwork.',
    category: 'Physical Health',
    date: new Date('2024-02-20'),
    time: '18:00',
    duration: 90,
    location: 'Los Angeles, CA',
    maxCapacity: 25,
    trainer: '2',
    status: 'published',
    registrations: [
      { userId: '4', status: 'booked', registeredAt: new Date('2024-02-05') },
      { userId: '5', status: 'interested', registeredAt: new Date('2024-02-08') },
    ],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    _id: '3',
    title: 'Nutrition & Wellness',
    description: 'Discover how proper nutrition impacts your happiness and overall well-being.',
    category: 'Health',
    date: new Date('2024-02-25'),
    time: '14:00',
    duration: 120,
    location: 'Chicago, IL',
    maxCapacity: 40,
    trainer: '2',
    status: 'published',
    registrations: [
      { userId: '4', status: 'booked', registeredAt: new Date('2024-02-02') },
    ],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-02'),
  },
];

export const mockCertificates: ICertificate[] = [
  {
    _id: '1',
    userId: '4',
    workshopId: '1',
    workshopTitle: 'Mindfulness & Meditation Basics',
    trainerName: 'Dr. Sarah Johnson',
    issuedDate: new Date('2024-02-15'),
    certificateNumber: 'HWBD-2024-001-EMMA',
    status: 'issued',
    sharedOn: ['twitter', 'linkedin'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-16'),
  },
  {
    _id: '2',
    userId: '5',
    workshopId: '1',
    workshopTitle: 'Mindfulness & Meditation Basics',
    trainerName: 'Dr. Sarah Johnson',
    issuedDate: new Date('2024-02-15'),
    certificateNumber: 'HWBD-2024-001-BASIAK',
    status: 'issued',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockTestimonials: ITestimonial[] = [
  {
    _id: '1',
    userId: '4',
    userName: 'Emma Wilson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    workshopId: '1',
    rating: 5,
    text: 'This workshop completely changed my perspective on happiness. Dr. Sarah is an amazing instructor!',
    isPublished: true,
    createdAt: new Date('2024-02-16'),
    updatedAt: new Date('2024-02-16'),
  },
  {
    _id: '2',
    userId: '5',
    userName: 'Basiak',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=basiak',
    workshopId: '1',
    rating: 5,
    text: 'The ny oath entertainment! The ny oath entertainist!',
    isPublished: true,
    createdAt: new Date('2024-02-16'),
    updatedAt: new Date('2024-02-16'),
  },
];

export const mockFeedback: IFeedback[] = [
  {
    _id: '1',
    userId: '4',
    workshopId: '1',
    rating: 5,
    comments: 'Excellent workshop with practical techniques',
    improvements: ['More interactive exercises', 'Longer sessions'],
    likelihood: 9,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];

export const mockAnalytics: IAnalytics = {
  date: new Date('2024-02-02'),
  totalUsers: 5,
  totalWorkshops: 3,
  totalAttendances: 6,
  averageHappiness: 8.38,
  happinessTrend: [
    { date: new Date('2024-01-01'), score: 7.2 },
    { date: new Date('2024-01-08'), score: 7.5 },
    { date: new Date('2024-01-15'), score: 7.8 },
    { date: new Date('2024-01-22'), score: 8.0 },
    { date: new Date('2024-01-29'), score: 8.2 },
    { date: new Date('2024-02-02'), score: 8.38 },
  ],
  emotionBreakdown: [
    { emoji: '😊', count: 65, percentage: 45 },
    { emoji: '😍', count: 55, percentage: 38 },
    { emoji: '😎', count: 25, percentage: 17 },
  ],
  createdAt: new Date('2024-02-02'),
  updatedAt: new Date('2024-02-02'),
};

export const mockDatabase = {
  users: mockUsers,
  workshops: mockWorkshops,
  certificates: mockCertificates,
  testimonials: mockTestimonials,
  feedback: mockFeedback,
  analytics: mockAnalytics,
};
