export interface RolePermissions {
  read: string[];
  write: string[];
  delete: string[];
  approve: string[];
  manage: string[];
}

export const rolePermissions = {
  VOLUNTEER: {
    read: ['bookings', 'workshops', 'certificates', 'feedback'],
    write: ['feedback', 'testimonials'],
    delete: [],
    approve: [],
    manage: [],
  },
  TRAINER: {
    read: ['bookings', 'workshops', 'analytics', 'trainers', 'certificates', 'feedback'],
    write: ['workshops', 'feedback', 'testimonials'],
    delete: ['workshops'],
    approve: [],
    manage: ['workshops'],
  },
  PARTICIPANT: {
    read: ['bookings', 'workshops', 'certificates', 'feedback', 'emotion-tracking'],
    write: ['bookings', 'feedback', 'testimonials', 'emotion-tracking'],
    delete: ['bookings'],
    approve: [],
    manage: [],
  },
  PARTNER: {
    read: ['bookings', 'workshops', 'analytics', 'workshop-requests', 'trainers', 'team'],
    write: ['workshops', 'workshop-requests', 'team', 'feedback'],
    delete: ['workshop-requests'],
    approve: [],
    manage: ['workshops', 'workshop-requests', 'team'],
  },
  DONOR: {
    read: ['analytics', 'impact-metrics', 'workshops', 'testimonials', 'reports'],
    write: [],
    delete: [],
    approve: [],
    manage: [],
  },
  RWA: {
    read: ['bookings', 'workshops', 'analytics', 'workshop-requests', 'trainers', 'venue'],
    write: ['workshops', 'workshop-requests', 'venue', 'feedback'],
    delete: ['workshop-requests'],
    approve: [],
    manage: ['workshops', 'workshop-requests', 'venue'],
  },
  ADMIN: {
    read: [
      'bookings',
      'workshops',
      'analytics',
      'workshop-requests',
      'trainers',
      'trainer-applications',
      'email-templates',
      'testimonials',
      'feedback',
      'certificates',
    ],
    write: [
      'workshops',
      'workshop-requests',
      'trainers',
      'email-templates',
      'feedback',
      'testimonials',
    ],
    delete: ['workshops', 'trainer-applications', 'workshop-requests'],
    approve: ['trainers', 'workshops', 'workshop-requests'],
    manage: [
      'workshops',
      'trainers',
      'workshop-requests',
      'trainer-applications',
      'email-templates',
      'system',
    ],
  },
  PHD_SCHOLAR: {
    read: ['bookings', 'workshops', 'analytics', 'certificates', 'feedback', 'research-data'],
    write: ['bookings', 'feedback', 'testimonials', 'research-data'],
    delete: ['bookings'],
    approve: [],
    manage: [],
  },
  DIRECTOR: {
    read: [
      'bookings',
      'workshops',
      'analytics',
      'workshop-requests',
      'trainers',
      'trainer-applications',
      'testimonials',
      'feedback',
      'strategic-reports',
      'team',
    ],
    write: [
      'workshops',
      'workshop-requests',
      'trainers',
      'feedback',
      'testimonials',
      'team',
    ],
    delete: ['workshops', 'trainer-applications', 'workshop-requests'],
    approve: ['trainers', 'workshops', 'workshop-requests'],
    manage: [
      'workshops',
      'trainers',
      'workshop-requests',
      'trainer-applications',
      'team',
      'strategic-operations',
    ],
  },
  CO_ADMIN: {
    read: [
      'bookings',
      'workshops',
      'analytics',
      'workshop-requests',
      'trainers',
      'trainer-applications',
      'email-templates',
      'testimonials',
      'feedback',
      'certificates',
      'team',
    ],
    write: [
      'workshops',
      'workshop-requests',
      'trainers',
      'email-templates',
      'feedback',
      'testimonials',
      'team',
    ],
    delete: ['workshops', 'trainer-applications', 'workshop-requests'],
    approve: ['trainers', 'workshops', 'workshop-requests'],
    manage: [
      'workshops',
      'trainers',
      'workshop-requests',
      'trainer-applications',
      'email-templates',
      'team',
    ],
  },
};
